import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import "./globals.css";
import {twMerge} from "tailwind-merge";

const dmSans = DM_Sans({subsets: ["latin"]});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={twMerge(dmSans.className, "antialiased")}
      >
        {children}
      </body>
    </html>
  );
}
